# Copyright(C) 2018 Hex Five Security, Inc. - All Rights Reserved

.PHONY: all
all: 
	java -jar multizone.jar ../zone1/zone1.hex ../zone2/zone2.hex ../zone3/zone3.hex ../zone4/zone4.hex --arch=$(BOARD)

.PHONY: clean
clean:
	rm -f multizone.hex
